name: CI-CD
on: [push]
jobs:

  ci-cd:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build front
        run: npm run build

      - name: Run tests
        run: npm run test-local

      - name: Deploy to render

        uses: johnbeynon/render-deploy-action@v0.0.8
        
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEYS }} 